#!/bin/bash
# Set the interval on com.google.keystone.agent.plist to 0 to prevent chrome from auto-updating in the background
# Jennifer Unger 08-04-2015


user=`ls -la /dev/console | cut -d " " -f 4`


defaults write /Users/$user/Library/Preferences/com.google.Keystone.Agent.plist checkInterval 0

