#!/bin/sh

# extension attribute to search for a hot corner set to disable screen saver.  You can modify it to search for any setting by changing the value of the 'setting' variable below.  
# created by Jennifer Unger
#
# Key wvous-$$-corner in the com.apple.dock plist designates this value.  
# $$is equal to the corner in question, Tl-top left, TR-top right, BL-bottom left, BR-bottom right
# This can be modified to search for any value set as a hot corner.  
# Values are as follows (as seen on a 10.10.2 system March 2015)
# 1 = Null
# 2= Mission Control
# 3= Application Windows
# 4= Desktop
# 5= Start Screen Saver
# 6= Disable Screen Saver
# 7= Dashboard
# 10= Display Sleep
# 11= Launch Pad
# 12= Notification Center



#get the current user

loggedInUser=`python -c 'from SystemConfiguration import SCDynamicStoreCopyConsoleUser; import sys; username = (SCDynamicStoreCopyConsoleUser(None, None, None) or [None])[0]; username = [username,""][username in [u"loginwindow", None, u""]]; sys.stdout.write(username + "\n");'`



#Get the current Value

BL=`defaults read /Users/$loggedInUser/Library/Preferences/com.apple.dock.plist wvous-bl-corner`
TL=`defaults read /Users/$loggedInUser/Library/Preferences/com.apple.dock.plist wvous-tl-corner`
TR=`defaults read /Users/$loggedInUser/Library/Preferences/com.apple.dock.plist wvous-tr-corner`
BR=`defaults read /Users/$loggedInUser/Library/Preferences/com.apple.dock.plist wvous-br-corner`
	


if [[ "$TL" = "6" ]]; then
	echo "<result>Yes</result>"
elif [[ "$BL" = "6" ]]; then
	echo "<result>Yes</result>"
elif [[ "$TR" = "6" ]]; then
	echo "<result>Yes</result>"
elif [[ "$BR" = "6" ]]; then
	echo "<result>Yes</result>"		
else
	echo "<result>No</result>"
fi

exit 0
